[phases.setup]
nixPkgs = ["nodejs_18"]
aptPkgs = []

[phases.build]
cmds = ["chmod +x build.sh", "./build.sh"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NIXPACKS_NO_DEFAULT_PHASES = "true"
